//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.Go4_PaymentService"/> </summary
    public sealed class Go4_PaymentServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public Go4_PaymentServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Go4_PaymentService";
            }
        }
        
        /// <summary>
        /// Call the BeginNfcPayment method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.BeginNfcPayment"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Go4.Nfc.Common.MagtekBeginPaymentResponse> BeginNfcPayment(Beamable.Go4.Nfc.Common.MagtekBeginPaymentRequest request)
        {
            string serialized_request = this.SerializeArgument<Beamable.Go4.Nfc.Common.MagtekBeginPaymentRequest>(request);
            string[] serializedFields = new string[] {
                    serialized_request};
            return this.Request<Beamable.Go4.Nfc.Common.MagtekBeginPaymentResponse>("Go4_PaymentService", "BeginNfcPayment", serializedFields);
        }
        
        /// <summary>
        /// Call the FinishNfcPayment method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.FinishNfcPayment"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Go4.Nfc.Common.MagtekFinishPaymentResponse> FinishNfcPayment(Beamable.Go4.Nfc.Common.MagtekFinishPaymentRequest request)
        {
            string serialized_request = this.SerializeArgument<Beamable.Go4.Nfc.Common.MagtekFinishPaymentRequest>(request);
            string[] serializedFields = new string[] {
                    serialized_request};
            return this.Request<Beamable.Go4.Nfc.Common.MagtekFinishPaymentResponse>("Go4_PaymentService", "FinishNfcPayment", serializedFields);
        }
        
        /// <summary>
        /// Call the Admin_ForceFulfillNfcPayment method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.Admin_ForceFulfillNfcPayment"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Go4.Nfc.Common.MagtekFinishPaymentResponse> Admin_ForceFulfillNfcPayment(string paymentId)
        {
            string serialized_paymentId = this.SerializeArgument<string>(paymentId);
            string[] serializedFields = new string[] {
                    serialized_paymentId};
            return this.Request<Beamable.Go4.Nfc.Common.MagtekFinishPaymentResponse>("Go4_PaymentService", "Admin_ForceFulfillNfcPayment", serializedFields);
        }
        
        /// <summary>
        /// Call the Admin_RefundNfcPayment method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.Admin_RefundNfcPayment"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Go4.Nfc.Common.MagtekRefundResponse> Admin_RefundNfcPayment(string paymentId)
        {
            string serialized_paymentId = this.SerializeArgument<string>(paymentId);
            string[] serializedFields = new string[] {
                    serialized_paymentId};
            return this.Request<Beamable.Go4.Nfc.Common.MagtekRefundResponse>("Go4_PaymentService", "Admin_RefundNfcPayment", serializedFields);
        }
        
        /// <summary>
        /// Call the Admin_GetPlayerPayments method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.Admin_GetPlayerPayments"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentDocument>> Admin_GetPlayerPayments(long gamerTag, int offset, int limit)
        {
            string serialized_gamerTag = this.SerializeArgument<long>(gamerTag);
            string serialized_offset = this.SerializeArgument<int>(offset);
            string serialized_limit = this.SerializeArgument<int>(limit);
            string[] serializedFields = new string[] {
                    serialized_gamerTag,
                    serialized_offset,
                    serialized_limit};
            return this.Request<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentDocument>>("Go4_PaymentService", "Admin_GetPlayerPayments", serializedFields);
        }
        
        /// <summary>
        /// Call the Admin_GetPayment method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.Admin_GetPayment"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentDocument>> Admin_GetPayment(string paymentId)
        {
            string serialized_paymentId = this.SerializeArgument<string>(paymentId);
            string[] serializedFields = new string[] {
                    serialized_paymentId};
            return this.Request<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentDocument>>("Go4_PaymentService", "Admin_GetPayment", serializedFields);
        }
        
        /// <summary>
        /// Call the Admin_GetPaymentAuditTrail method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.Admin_GetPaymentAuditTrail"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentEventDocument>> Admin_GetPaymentAuditTrail(string paymentId)
        {
            string serialized_paymentId = this.SerializeArgument<string>(paymentId);
            string[] serializedFields = new string[] {
                    serialized_paymentId};
            return this.Request<System.Collections.Generic.List<Beamable.Go4.Nfc.Common.NfcPaymentEventDocument>>("Go4_PaymentService", "Admin_GetPaymentAuditTrail", serializedFields);
        }
        
        /// <summary>
        /// Call the TestConcurrency method on the Go4_PaymentService microservice
        /// <see cref="Beamable.Microservices.Go4_PaymentService.TestConcurrency"/>
        /// </summary>
        public Beamable.Common.Promise<string> TestConcurrency()
        {
            string[] serializedFields = new string[0];
            return this.Request<string>("Go4_PaymentService", "TestConcurrency", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersGo4_PaymentServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterBeamable_Go4_Nfc_Common_MagtekBeginPaymentRequest : MicroserviceClientDataWrapper<Beamable.Go4.Nfc.Common.MagtekBeginPaymentRequest>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterBeamable_Go4_Nfc_Common_MagtekFinishPaymentRequest : MicroserviceClientDataWrapper<Beamable.Go4.Nfc.Common.MagtekFinishPaymentRequest>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForGo4_PaymentServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<Go4_PaymentServiceClient>();
        }
        
        public static Go4_PaymentServiceClient Go4_PaymentService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<Go4_PaymentServiceClient>();
        }
    }
}
